---
# handlers file for apache
- name: restart mem cached
  service:
    name: memcached
    state: restarted
  listen: "restart memcached"

- name: restart apache
  service:
    name: apache
    state: restarted
  listen: "restart apache"
