--- # Apache webserver Bootstrap
- name: install httpd
  yum:
    name: httpd
    state: latest
- name: create directory
  file:
    path: /var/www/html/
    state: touch 
- name: create file
  file:
    path: /var/www/html/index.html
    state: touch
- name: write inside index.html
  lineinfile:
    line: "<h1>Welcome to ... </h1>"
    path: /var/www/html/index.html
- name:
  template:
    src: template.j2
    dest: /etc/httpd/conf/httpd.conf
  notify:
    - restart memcached
    - restart apache
...
